version: "3.9"
services:
  # ---------- SQL Server ----------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "My_Passw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  # ---------- ArticleService with 3 replicas ----------
  article-service:
    image: happyheadlines/article-service
    depends_on:
      - sqlserver
    deploy:
      replicas: 3
    ports:
      - "8000:80"

  # ---------- Other services (single replica each) ----------
  draft-service:
    image: happyheadlines/draft-service
    depends_on:
      - sqlserver
    ports:
      - "8001:80"

  publisher-service:
    image: happyheadlines/publisher-service
    depends_on:
      - sqlserver
    ports:
      - "8002:80"
  comment-service:
    image: happyheadlines/comment-service
    depends_on:
      - sqlserver
    ports:
      - "8003:80"
  subscriber-service:
    image: happyheadlines/subscriber-service
    depends_on:
      - sqlserver
    ports:
      - "8004:80"
  
  profanity-service:
    image: happyheadlines/profanity-service
    depends_on:
      - sqlserver
    ports:
      - "8005:80"

  newsletter-service:
    image: happyheadlines/newsletter-service
    depends_on:
      - sqlserver
    ports:
      - "8006:80"


volumes:
  mssql-data:
