
services:
  # ---------- SQL Server ----------
  # run: docker-compose up -d (to auto load .env file)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssql-data:/var/opt/mssql

  # ---------- ArticleService with 3 replicas ----------
  article-service:
    image: happyheadlines/article-service
    depends_on:
      - sqlserver
    environment:
      DATABASE_NAME: ${ARTICLE_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    deploy:
      replicas: 3
    ports:
      - "8000:80"

  # ---------- Other services (single replica each) ----------
  draft-service:
    image: happyheadlines/draft-service
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      DATABASE_NAME: ${DRAFT_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8010:80"

  publisher-service:
    image: happyheadlines/publisher-service
    depends_on:
      - sqlserver
    environment:
      DATABASE_NAME: ${PUBLISHER_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8002:80"
  comment-service:
    image: happyheadlines/comment-service
    depends_on:
      - sqlserver
      - profanity-service
    environment:
      DATABASE_NAME: ${COMMENT_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8003:80"
  subscriber-service:
    image: happyheadlines/subscriber-service
    depends_on:
      - sqlserver
    environment:
      DATABASE_NAME: ${SUBSCRIBER_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8004:80"
  
  profanity-service:
    image: happyheadlines/profanity-service
    depends_on:
      - sqlserver
    environment:
      DATABASE_NAME: ${PROFANITY_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8005:80"

  newsletter-service:
    image: happyheadlines/newsletter-service
    depends_on:
      - sqlserver
    environment:
      DATABASE_NAME: ${NEWSLETTER_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "8006:80"

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672" #AMQP Protocol
    - "15672:15672" #Management UI


volumes:
  mssql-data:
