name: Devops Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: ${{secrets.SA_PASSWORD}}
    
    steps:
    #1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    #2. Set image tag based on commit SHA
    - name: Set image tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
    
    #3. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/Setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
      
      #4. Build and push docker images for all services
    - name: Build and push docker images
      working-directory: ${{ github.workspace }}
      run: |
        services=(article-service draft-service publisher-service comment-service subscriber-service profanity-service newsletter-service)
        for service in "${services[@]}"; do
          case $service in
            article-service) folder=ArticleService ;;
            draft-service) folder=DraftService ;;
            publisher-service) folder=PublisherService ;;
            comment-service) folder=CommentService ;;
            subscriber-service) folder=SubscriberService ;;
            profanity-service) folder=ProfanityService ;;
            newsletter-service) folder=NewsletterService ;;
          esac

          echo "Building $service from ./src/$folder"
          docker build -t happyheadlines/$service:$IMAGE_TAG -f src/$folder/Dockerfile .
          docker push happyheadlines/$service:$IMAGE_TAG
          docker tag happyheadlines/$service:$IMAGE_TAG happyheadlines/$service:latest
          docker push happyheadlines/$service:latest
        done
      env:
        IMAGE_TAG: ${{ github.sha }}

    #5. Deploy using docker compose
    - name: Deploy services
      run: |
        docker-compose pull
        IMAGE_TAG=$IMAGE_TAG docker-compose up -d --build