name: Devops Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - service: article-service
              folder: ArticleService
            - service: draft-service
              folder: DraftService
            - service: publisher-service
              folder: PublisherService
            - service: comment-service
              folder: CommentService
            - service: subscriber-service
              folder: SubscriberService
            - service: profanity-service
              folder: ProfanityService
            - service: newsletter-service
              folder: NewsletterService
    continue-on-error: true
    env:
      IMAGE_TAG: ${{github.sha}}
      GHCR_REGISTRY: ghcr.io
      GHCR_OWNER: ${{ github.repository_owner }}
      GHCR_PAT: ${{secrets.GHCR_PAT}}
      DOCKER_REGISTRY: happyheadlines
      SA_PASSWORD: ${{secrets.SA_PASSWORD}}
    
    steps:
      #Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

      #Login to GHCR
    - name: Login to GHCR
      run: echo "${{ env.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
      #Build and push docker images for all services
    - name: Build and push microservices
      uses: docker/build-push-action@v6
      with:
        #Build all microservices in sequence
        push: true
        context: .
        file: src/${{ matrix.folder }}/Dockerfile
        #Args will be overriden in matrix below
        tags: |
            ${{ env.GHCR_REGISTRY }}/${{ /larskan }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}
            ${{ env.GHCR_REGISTRY }}/${{ /larskan }}/${{ matrix.service }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy services
        run: |
          docker-compose pull
          IMAGE_TAG=${{ github.sha }} docker-compose up -d --build